import first from "./first.svg"
import second from "./second.svg"
import third from "./third.svg"
import fourth from "./fourth.svg"
import fifth from "./fifth.svg"
import sixth from "./sixth.svg"
import gmail from "./gmail.svg"
import whatsapp from "./whatsapp.svg"
import linkedin from "./linkedin.svg"
import send from "./send.svg"
import twitter from "./x.svg"
export { fifth, second, first, fourth, sixth, third, linkedin, send, whatsapp, gmail, twitter }
